# Multi-Task Dataset Configuration for Vintix (Go2 + Minicheetah)

go2_walking_ad:
  type: "default"
  path: "go2_trajectories/data_1M"  # data/go2_trajectories/data_1M (AD data with p=0.6, f=0.05, 1M steps per env, no data leakage)
  group: "go2_locomotion"
  reward_scale: 1.0
  episode_sparsity: 1

minicheetah_walking_ad:
  type: "default"
  path: "minicheetah_trajectories/minicheetah_ad"  # data/minicheetah_trajectories/minicheetah_ad (AD data with p=0.6, f=0.05, 1M steps per env)
  group: "minicheetah_locomotion"
  reward_scale: 1.0
  episode_sparsity: 1

